spring:
  data:
    mongodb:
      username: mango
      password: mango
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
  docker:
      compose:
        enabled: true
        file: docker-compose.yml
server:
    port: 8088
